import fs from 'node:fs/promises'
import path from 'node:path'
import { fileTypeFromFile } from 'file-type'
import Conversion from '../models/Conversion.js'
import File from '../models/File.js'
import { getConverter } from '../converters/index.js'
import { categoryFrom,safeExt,removeQuietly } from '../utils/files.js'
import { conversionQueue } from '../services/queue.js'

export async function convert(req,res,next){if(!req.file)return res.status(400).json({message:'Choose a file to convert'});const target=String(req.body.targetFormat||'').toLowerCase().replace(/^\./,'');if(!/^[a-z0-9]{1,8}$/.test(target)){await removeQuietly(req.file.path);return res.status(400).json({message:'A valid target format is required'})}const detected=await fileTypeFromFile(req.file.path).catch(()=>null);const source=detected?.ext||safeExt(req.file.originalname);const mime=detected?.mime||req.file.mimetype;const category=categoryFrom(mime,source);let record;const start=Date.now();try{const plugin=getConverter(category,source,target);const file=await File.create({filename:req.file.filename,originalName:req.file.originalname,originalFormat:source,outputFormat:target,mimeType:mime,category,fileSize:req.file.size,storagePath:req.file.path,status:'processing',createdBy:req.user._id,expiresAt:new Date(Date.now()+Number(process.env.FILE_RETENTION_HOURS||24)*3600_000)});record=await Conversion.create({userId:req.user._id,inputFile:{originalName:req.file.originalname,filename:req.file.filename,format:source,size:req.file.size,path:req.file.path,category},conversionType:`${source}_to_${target}`,status:'processing'});const out=await conversionQueue.add(()=>plugin.convert(req.file.path,target,source));const stat=await fs.stat(out);const filename=path.basename(out);record.outputFile={originalName:`${path.parse(req.file.originalname).name}.${target}`,filename,format:target,size:stat.size,path:out,category};record.processingTime=Date.now()-start;record.status='completed';record.downloadUrl=`/downloads/${encodeURIComponent(filename)}`;await record.save();file.status='completed';await file.save();res.status(201).json({conversion:record})}catch(error){if(record){record.status='failed';record.error=error.message;record.processingTime=Date.now()-start;await record.save().catch(()=>{})}await removeQuietly(req.file.path);next(error)}}
export async function history(req,res){const filter={userId:req.user._id};if(req.query.status)filter.status=req.query.status;if(req.query.search)filter['inputFile.originalName']={$regex:String(req.query.search).replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),$options:'i'};const limit=Math.min(Number(req.query.limit||100),100);const [recent,total,successful,storageAgg,favorites]=await Promise.all([Conversion.find(filter).sort('-createdAt').limit(limit).lean(),Conversion.countDocuments({userId:req.user._id}),Conversion.countDocuments({userId:req.user._id,status:'completed'}),Conversion.aggregate([{$match:{userId:req.user._id,status:'completed'}},{$group:{_id:null,n:{$sum:'$outputFile.size'}}}]),Conversion.countDocuments({userId:req.user._id,favorite:true})]);res.json({recent,stats:{total,successful,storage:storageAgg[0]?.n||0,favorites}})}
export async function removeHistory(req,res){const item=await Conversion.findOne({_id:req.params.id,userId:req.user._id});if(!item)return res.status(404).json({message:'Conversion not found'});await removeQuietly(item.inputFile?.path,item.outputFile?.path);await File.deleteMany({createdBy:req.user._id,filename:item.inputFile?.filename});await item.deleteOne();res.status(204).end()}
